# Generated by Django 5.1.1 on 2024-09-10 04:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionDirectory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('version', models.CharField(db_index=True, max_length=50, verbose_name='Версия')),
                ('created_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата начала действия версии')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='service_api.directory', verbose_name='Идентификатор справочника')),
            ],
            options={
                'verbose_name': 'Версия справочника',
                'verbose_name_plural': 'Версии справочника',
                'constraints': [models.UniqueConstraint(fields=('directory', 'version'), name='version_constraint'), models.UniqueConstraint(fields=('directory', 'created_date'), name='date_constraint')],
            },
        ),
    ]
