# Generated by Django 5.1.1 on 2024-09-10 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0002_versiondirectory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('code', models.CharField(max_length=100, verbose_name='Код элемента')),
                ('value', models.CharField(max_length=300, verbose_name='Значение элемента')),
                ('version_directory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='service_api.versiondirectory', verbose_name='Идентификатор Версии справочника')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
                'constraints': [models.UniqueConstraint(fields=('version_directory', 'code'), name='code_constraint')],
            },
        ),
    ]
